name: Publish Storybook and Typedoc

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4.1.0

      - uses: actions/setup-node@v4
        with:
          # https://nodejs.org/en/about/previous-releases
          node-version: 22.15.0

      - run: pnpm install

      - run: |
          pnpm build
          pnpm typedoc

      - run: |
          mkdir -p build/sites
          mv ./examples/storybook/storybook-static ./build/sites/storybook
          mv ./build/typedocs ./build/sites/typedocs

      - uses: actions/upload-pages-artifact@v3
        id: deployment
        with:
          path: ./build/sites

  deploy:
    name: Deploy docs
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    permissions:
      pages: write
      id-token: write

    steps:
      # https://github.com/actions/deploy-pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
