name: Publish Storybook

on:
  push:
    branches:
      - main
      - typedoc

jobs:
  deploy_storybook:
    name: Publish Storybook
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3.0.0
        with:
          version: 8

      - uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - run: pnpm install

      - run: |
          pnpm build
          pnpm typedoc

      - run: |
          mkdir -p build/sites
          mv ./examples/storybook/storybook-static ./build/sites/storybook
          mv ./build/typedocs ./build/sites/typedocs

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/sites
          cname: react-playground.docs.kitsuyui.com
