name: test-vrt
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    runs-on: macos-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4.1.0

      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install

      - name: Test build
        run: pnpm build

      - name: Visual Regression Test
        run: pnpm test:vrt
        env:
          CI: true

      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-report
          path: examples/storybook/playwright-report/
          retention-days: 1
