name: test-vrt
on:
  - pull_request
jobs:
  test:
    runs-on: macos-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: yarn
          cache-dependency-path: yarn.lock

      - name: Cache playwright
        id: cache-vrt-macos
        uses: actions/cache@v3
        with:
          path: ~/Library/Caches/ms-playwright
          key: ${{ runner.os }}-build-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashFiles('**/yarn.lock') }}
            ${{ runner.os }}-build-

      - name: Install dependencies
        run: |
          yarn install
          ./yarn.links.sh
          npx playwright install

      - name: Test
        run: yarn build

      - name: Visual Regression Test
        run: yarn test:vrt

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: playwright-report
          path: examples/storybook/playwright-report/
          retention-days: 1
