name: test-vrt
on:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    runs-on: macos-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8

      - uses: actions/setup-node@v3
        with:
          node-version: latest
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Install dependencies
        run: |
          pnpm prune
          pnpm install
          ./pnpm.links.sh

      - name: Test
        run: pnpm build

      - name: Visual Regression Test
        run: pnpm test:vrt

      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: playwright-report
          path: examples/storybook/playwright-report/
          retention-days: 1
